apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  ports:
    - name: admin
      protocol: TCP
      port: 14271
      targetPort: 8080
    # - name: default
    #   protocol: TCP
    #   port: 14267
    #   targetPort: 14267
    - name: grcp
      protocol: TCP
      port: 14250
    - name: thrift
      protocol: TCP
      port: 14268
