apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: prod-mongo
spec:
  selector:
    matchLabels:
      app: prod-mongo
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: order-history-config
            optional: false
        image: mongo
        imagePullPolicy: Always
        name: mongodb
        ports:
          - containerPort: 27017
            name: http
            protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File            
