apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  annotations:
    viz.linkerd.io/tap-enabled: true
spec:
  template:
    spec:
      containers:
      - image: redis:6.2.13-alpine3.18
        imagePullPolicy: Always
        name: redis
        ports:
          - containerPort: 6379
            name: http
            protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
