apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-deployment
  annotations:
    viz.linkerd.io/tap-enabled: true
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
