apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
  sessionAffinity: None
  type: ClusterIP
