apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix-canary
  namespace: prod-remix
spec:
  replicas: 1
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: remix-config
            optional: false
        image: 902342763241.dkr.ecr.us-west-2.amazonaws.com/remix-test:canary
        imagePullPolicy: Always
        name: blues-remix
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        securityContext:
          privileged: false        