namespace: prod-remix
resources:
  - prod-ingress.yaml
  - rollout.yaml
  - canary-service.yaml
  - canary-deployment.yaml
configMapGenerator:
  - name: remix-config
    env: config.properties
commonLabels:
  app: remix
