apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.48
        args: ["--query.http-server.host-port=10.244.0.69:4317"]
        ports:
        - containerPort: 16686