apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-service
spec:
  ports:
    - name: default
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: health
      protocol: TCP
      port: 16687
    - name: query
      protocol: TCP
      port: 4317
