namespace: prod-remix
namePrefix: prod-
resources:
  - ../../base
  - prod-ingress.yaml
  - sealed-secret.json
patchesStrategicMerge:
  - prod-service.yaml
  - prod-deployment.yaml
configMapGenerator:
  - name: remix-config
    env: config.properties
